variables:
  CONAN_PACKAGE_NAME: qbjs_deserializer
  CONAN_RECIPE_VERSION: 0.0.5-0
  CONAN_USER: gitlab-ci
  CONAN_CHANNEL: test

conan-create-package-linux:
  tags: [saas-linux-small-amd64]
  image: python:3.10.7-alpine3.16
  stage: build
  before_script:
    - pip install conan
    - pip install cmake
    - apk update
    - apk add curl
    - apk add gcc
    - apk add g++
    - apk add make
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source "$HOME/.cargo/env"
    - gcc --version
    - g++ --version
    - rustc --version
    - conan --version
    - cmake --version
    - make --version
  script:
    - conan create cpp_packaging/conanfile.py $CONAN_PACKAGE_NAME/$RECIPE_VERSION@$CONAN_USER/$CONAN_CHANNEL -s compiler="gcc" -s compiler.version="11" -s compiler.libcxx="libstdc++" -s build_type="Release"

conan-create-package-windows:
  tags: [windows]
  stage: build
  before_script:
    - choco feature enable -n allowGlobalConfirmation
    - choco install python3
    - $Env:PATH = "C:\Python311\Scripts;$Env:PATH"
    - refreshenv
    - py -m pip install --upgrade pip
    - py -m pip install conan
    - py -m pip install cmake
    - choco install rustup.install  --ignore-checksums
    - $Env:PATH = "$Env:USERPROFILE\.cargo\bin;$Env:PATH"
    - refreshenv
    - conan --version
    - cmake --version
    - rustc --version
    - cargo --version
  script:
    - conan create cpp_packaging/conanfile.py $Env:CONAN_PACKAGE_NAME/$Env:RECIPE_VERSION@$Env:CONAN_USER/$Env:CONAN_CHANNEL -s compiler="Visual Studio" -s compiler.version="16" -s compiler.cppstd="14" -s build_type="Release"

conan-create-package-macos:
  tags: [shared-macos-amd64]
  image: macos-12-xcode-14
  stage: build
  before_script:
    - python3.9 -m pip install --upgrade pip
    - python3.9 -m pip install --upgrade conan
    - python3.9 -m pip install --upgrade cmake
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && source "$HOME/.cargo/env"
    - clang --version
    - clang++ --version
    - rustc --version
    - conan --version
    - cmake --version
  script:
    - conan create cpp_packaging/conanfile.py $CONAN_PACKAGE_NAME/$RECIPE_VERSION@$CONAN_USER/$CONAN_CHANNEL -s compiler="apple-clang" -s compiler.version="14" -s compiler.cppstd="14" -s compiler.libcxx="libc++" -s build_type="Release"
